config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'jobs#index'
  resources :jobs, except: :index
  resources :questions

  #workshop

  get '/workshop/', to: 'pages#workshop'
  get '/qa/', to: 'pages#qa'
  get '/trabajo/', to: 'pages#trabajo'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/companyprofile.rb
class Companyprofile < ApplicationRecord
  belongs_to :job

end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  extend FriendlyId
  friendly_id :slug_jobs, use: :slugged

  def slug_jobs
    [
      :title,
      %i[title company]
    ]
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  # include Pundit

  # # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def default_url_options
    { host: ENV['HOST'] || 'localhost:3000' }
  end

  BRAND_NAME = 'Nowmada'

  def meta_title(title)
    [title, BRAND_NAME].reject(&:empty?).join(' | ')
  end

  #   def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/companyprofiles_controller.rb
class CompanyprofilesController < ApplicationController
  def index
    @jobs = Job.all
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

require 'date'

class JobsController < ApplicationController
  attr_accessor :slug
  before_action :set_job, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index

    @weekjobs = Job.past_week.order("created_at DESC")
    @alljobs = Job.before(Date.today - 7 ).distinct.order("created_at DESC")
    @user = current_user
    @meta_title = meta_title 'Portal de empleo remoto y recursos en español'
    @question = Question.new
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to @job
    else
      render :new
    end
  end

  def edit
    @job = Job.friendly.find(params[:id])
  end

  def update
    @job = Job.friendly.find(params[:id])
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @job  = Job.friendly.find(params[:id])
    @user = current_user
    @meta_title = meta_title "Trabajo remoto #{@job.category} @ #{@job.company.capitalize}"
  end

  def destroy
    @job = Job.friendly.find(params[:id])
    @job.destroy
    redirect_to root_path, notice: 'job was successfully destroyed.'
  end

  private

  def set_job
    @job = Job.friendly.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :company, :desc, :url, :contact,
                                :category, :photo, :photo_cache, :slug , :language)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[trabajo workshop]

  def workshop
  end

  def trabajo
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @question = Question.new
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/companyprofiles_helper.rb
module CompanyprofilesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
end

app/helpers/meta_tags_helper.rb
# frozen_string_literal: true

# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image'])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?('http') ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/companyprofiles/show.html.erb
<div class="wrapper">
  <h1><%= company.job.name %></h1>
</div>

app/views/jobs/edit.html.erb
<h1>Edit the job in the DB</h1>

<%= simple_form_for @job do |f| %>
  <%= f.input :title %>
  <%= f.input :company %>
  <%= f.input :desc, as: :text, autofocus: true, :input_html => {:style => 'width: 100%', :rows => 5}%>
  <%= f.input :url %>
  <%= f.input :category, collection: [ "diseño", "marketing", "Tech", "atención al Cliente" , "asistente Virtual" , "traducción", "UX" , "contenido"]%>
  <%= f.input :language, collection: [ "Castellano", "Inglés","Castellano & Inglés" ]%>
  <%= f.input :contact %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/jobs/index.html.erb
<div class="banner" style="background-image: url('<%= image_path("bgmain.jpg")%>');">
  <div class="tagline">

    <h1>  Portal de empleo remoto en español
    </h1>
    <p> Recibe las últimas ofertas cada semana</p>

    <form action="https://nowmada.us17.list-manage.com/subscribe/post?u=06681d916dc998e5e02141ce6&amp;id=299f6fa8b7" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
      <div id="mc_embed_signup_scroll">

        <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email@email.com" required>
        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups - ok-->
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_06681d916dc998e5e02141ce6_299f6fa8b7" tabindex="-1" value=""></div>
        <div class="clear"><input type="submit" value="Subscríbete" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
      </div>
    </form>

  </div>
</div>

<div class="wrapperjob">
  <div class="jobcontent">
   <!-- <div class="jobbox"> -->

    <div class="jobdetailsright">


      <ul>
        <ol class ="datetitle" id="time">
          <p>Últimas oportunidades</p>
        </ol>
        <% @weekjobs.each do |job| %>
        <%=link_to job_path(job) do%>
        <ol class ="card">

          <div class="photocard">
            <%= cl_image_tag job.photo, height: 50, width: 50, crop: :fill %>
          </div>

          <div class="jobtitle">
            <h5>
              <%=job.title%>
            </h5>
            <p><span style="color:#777676;font-size: 13px">
              <%=job.company%>
              </span> </p>
            <p><span style="color:#cc3838;font-size: 13px;border: solid 2px;padding: 0.25em">
              <%=job.category.capitalize%></span>
              <span style="color:#1c86cc;font-size: 13px;border: solid 2px;padding: 0.25em"><%=job.language%></span>
               </p>
            </div>
            <div class="date">
              <p small><span style="color:#000;font-style:italic;font-size: 9px";>
                <% days = (Date.today - job.created_at.to_date).to_i  %>
                Publicado <%= days %> día(s)</span>
              </p>
            </div>
          </ol>
          <% end %>
        <% end %>
        <ol class="card">
          <div class="question">
          <%= render "questions/new" %>
          </div>
        </ol>
        </ul>

       <div class="jobdetailsright">

        <ul>
          <ol class="card">
            <div class="question">
              <h5>Síguenos para acceder a las últimas oportunidades</h5>
              <div class="socialicon">
                <a href="https://www.facebook.com/groups/nowmada/" id= "socialicon" target="_blank">
                  <%= image_tag("fb.png", size: "50x50", target: '_blank') %>
                <a href="https://twitter.com/esnowmada" target="_blank">
                  <%= image_tag("twitter.png", size: "50x50", target: '_blank') %>
                </a>
                <a href="https://instagram.com/esnowmada" target="_blank">
                  <%= image_tag("insta.png", size: "40x40") %>

                </a>
              </div>
            </div>
          </ol>



          <ol class ="datetitle" id="time">
            <p>Oportunidades anteriores</p>
          </ol>
         <% @alljobs.each do |job| %>
         <%=link_to job_path(job) do%>
         <ol class ="card">

           <div class="photocard">
             <%= cl_image_tag job.photo, height: 50, width: 50, crop: :fill %>
           </div>

          <div class="jobtitle">
            <h5>
              <%=job.title%>
            </h5>
            <p><span style="color:#777676;font-size: 13px">
              <%=job.company%>
              </span> </p>
            <p><span style="color:#cc3838;font-size: 13px;border: solid 2px;padding: 0.25em">
              <%=job.category.capitalize%></span>
              <span style="color:#1c86cc;font-size: 13px;border: solid 2px;padding: 0.25em"><%=job.language%></span>
               </p>
            </div>
            <div class="date">
              <p small><span style="color:#000;font-style:italic;font-size: 9px";>
                <% days = (Date.today - job.created_at.to_date).to_i  %>
                Publicado <%= days %> día(s)</span>
              </p>
           </ol>
           <% end %>
           <% end %>
         </ul>
       </div>
       </div>
     </div>
   </div>

app/views/jobs/new.html.erb
<h1>Enter job in the DB</h1>

<%= simple_form_for @job do |f| %>
  <%= f.input :title %>
  <%= f.input :company %>
  <%= f.input :desc, as: :text, autofocus: true, :input_html => {:style => 'width: 100%', :rows => 5}%>
  <%= f.input :url %>
  <%= f.input :category, collection: [ "diseño", "marketing", "Tech", "atención al Cliente" , "asistente Virtual" , "traducción", "UX" , "contenido"]%>
  <%= f.input :language, collection: [ "Castellano", "Inglés","Castellano & Inglés" ]%>
  <%= f.input :contact %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/jobs/show.html.erb
<div class="wrapper">
  <div class="bannerblack">
    <div class="tagline">
      <h3>  Portal de empleo remoto en español</h3>
      <p> Recibe las últimas ofertas cada semana</p>
      <div class="formulaire">
       <form action="https://nowmada.us17.list-manage.com/subscribe/post?u=06681d916dc998e5e02141ce6&amp;id=299f6fa8b7" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div id="mc_embed_signup_scroll">

          <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email@email.com" required>

          <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_06681d916dc998e5e02141ce6_299f6fa8b7" tabindex="-1" value=""></div>
          <div class="clear"><input type="submit" value="Subscríbete" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
        </div>
      </form>
      </div>

</div>
  </div>
  <div class="wrapperjob">
        <h3><%= @job.title%> - <%= @job.company%></h3>
          <div class="description">
            <%= simple_format(@job.desc) %>
          </div>
          <div class="email">
            <p><%= @job.contact %></p>
          </div>
                  <% tweet = @job.title
            uri = Addressable::URI.parse(request.original_url).normalize
        %>


            <%= link_to 'tweet' , "https://twitter.com/intent/tweet?text=#{'Nueva Opportunidad: ' + tweet}&url=#{request.original_url}&hashtags=teletrabajo%2Ctrabajoremoto%2Cempleoremoto", class: 'twitter-share-button' %>
          <div class="apply">
            <%= link_to "Aplicar", "#{@job.url}?utm=nowmada",target: "_blank", class: 'btnshow'%>
            <%=link_to "Volver", root_path, class: 'btn btn-primary', class: 'btnshow'%>

            <div class="delete">
              <% if current_user && current_user.skills == false %>
                <%= link_to job_path(@job),
                  method: :delete, data: { confirm: 'Are you sure?' },
                  class: 'btn btn-danger' do %>
                    <p>Delete</p>
                  <% end %>
                <%= link_to 'Edit', edit_job_path, class: 'btn btn-success'%>
              <% end %>
             </div>
            </div>
          </div>
      </div>
    </div>
</div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= @meta_title ? @meta_title : ApplicationController::BRAND_NAME %></title>
<meta name="description" content="<%= meta_description %>">
<%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">
  <%= csrf_meta_tags %>

  <!-- Hotjar Tracking Code for www.nowmada.eu -->
<script>
(function(h,o,t,j,a,r){
h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
h._hjSettings={hjid:828519,hjsv:6};
a=o.getElementsByTagName('head')[0];
r=o.createElement('script');r.async=1;
r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
a.appendChild(r);
})(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>



<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T4N3MRV');</script>
<!-- End Google Tag Manager -->
<!-- Twitter -->
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>


  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-115418660-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-115418660-1');
</script>

</head>

<body>

  <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T4N3MRV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
  <%= yield %>
</body>
</html>

app/views/pages/qa.html.erb
<h1>List of things to check</h1>

<ul><strong>Check after each deployment if the following works</strong></ul>
<li>Check Mobile and destop rendering</li>
<li>Check if mailchimp form is working on homepage , job,  workshop and company</li>
<li>Check if apply button is working</li>
<li>Check if adding editing deleting a job is working</li>
<li>Check if annunciar un trabajo is working</li>

app/views/pages/trabajo.html.erb
<div class="wrapper">
  <div class="bannerblack-company">
    <div class="tagline">
      <h3>¿Quieres que tu empresa tenga acceso al mejor talento global de habla hispana? </h3>
          <h4>
            Publica tu oferta de trabajo en Nowmada y unete a la revolución del talento remoto en español.
          </h4>
          <div class="formulaire">
<form action="https://nowmada.us17.list-manage.com/subscribe/post?u=06681d916dc998e5e02141ce6&amp;id=d4601f9281" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">

              <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email@email.com" required>

              <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_06681d916dc998e5e02141ce6_d4601f9281" tabindex="-1" value=""></div>
              <div class="clear"><input type="submit" value="Saber más" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
            </div>
          </form>
          </div>
    </div>
  </div>
</div>

app/views/pages/workshop.html.erb
<!-- <div class="banner" style="background-image:linear-gradient(-225deg, rgba(192,192,170,0.6) 0%, rgba(126, 183, 246, 0.6) 50%), url('<%#= image_path("workshop.jpg")%>');">
  <div class="tagline "> -->
<div class="banner" style="background-image: url('<%= image_path("workshop.jpg")%>');">
  <div class="banner-workshop">
    <div class="tagline">

      <h3>Jornadas para Nómadas Digitales</h3>
      <h4>El futuro del Trabajo Remoto en Castellano</h4>

      <p>Este julio en Barcelona nómadas digitales, aspirantes y empresas se encontrarán para hablar sobre la situación del trabajo remoto en español.
     En este foro queremos dar espacio a la discusión, a la creación, al networking y al avance de esta nueva sociedad nómada hispana.</p>

    <!-- <p> Recibe las últimas ofertas cada semana</p> -->

  <form action="https://nowmada.us17.list-manage.com/subscribe/post?u=06681d916dc998e5e02141ce6&amp;id=f5369c9732" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
      <div id="mc_embed_signup_scroll">

        <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email@email.com" required>
        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups - ok-->
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_06681d916dc998e5e02141ce6_f5369c9732" tabindex="-1" value=""></div>
        <div class="clear"><input type="submit" value="Saber más" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
      </div>
    </form>
  </div>
</div>




<!--End mc_embed_signup-->

app/views/questions/_new.html.erb
<h5>I Jornadas de trabajo remoto en Barcelona</h5>
<%#= simple_form_for @question do |f| %>
  <%#= f.input :q1,  as: :radio_buttons%>
  <%#= f.button :submit %>
  <!-- Begin MailChimp Signup Form -->
  <%= link_to 'Saber más', workshop_path, class: 'btn btn-primary' %>
</div>

  <!--End mc_embed_signup-->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 79 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

  <%= link_to 'Anunciar un trabajo', trabajo_path, class: 'btn btn-primary' %>

    <% if user_signed_in? %>

    <!-- Links when logged in -->
    <%= link_to 'Add a new job', new_job_path, class: 'btn btn-primary' %>
    <%= link_to 'Q&A', qa_path, class: 'btn btn-primary' %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">

          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-danger'  do %>
          <%= t(".sign_out", default: "Log out") %>
          <% end %>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <%= link_to 'Add a new job', new_job_path, class: 'btn btn-primary' %>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>